version: '3.8'

services:
  rtk-bridge:
    build: .
    container_name: galileo_bridge
    command: >
      str2str -in ntrip://elenadr27:n!U6enetzY@euref-ip.net:2101/MATE00ITA0 
              -out tcpsvr://:9000
    ports:
      - "9000:9000"
    restart: always
